test, this should NOT work, white bg

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -156,30 +156,35 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
       - name: Check Quality Gate Status
-        id: quality_gate_check  # Add an ID to reference this step's outcome
         run: |
           curl -s -u ${{ secrets.SONAR_TOKEN }}: \
             "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Volenday_sample-for-sonar-test" \
             | jq -r '.projectStatus.status' > quality_gate_status.txt
           if [ "$(cat quality_gate_status.txt)" != "OK" ]; then
-            echo "Quality Gate failed."
-            echo "failed" > quality_gate_status.out
+            echo "Quality Gate failed. Failing the workflow."
+            exit 1
           else
             echo "Quality Gate passed."
-            echo "passed" > quality_gate_status.out
           fi
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
-      # Prevent deployment based on quality gate result
-      - name: Skip Vercel Deployment
-        run: |
-          QUALITY_GATE_STATUS=$(cat quality_gate_status.out)
-          if [ "$QUALITY_GATE_STATUS" = "failed" ]; then
-            echo "VERCEL_SKIP_DEPLOYMENT=true" >> $GITHUB_ENV
-            echo "Skipping Vercel deployment because the quality gate failed."
-            exit 1  # Fail the workflow
-          else
-            echo "Quality Gate passed. Proceeding with deployment."
-          fi
+      # # Prevent deployment on failure
+      # - name: Skip Vercel Deployment on Failure
+      #   if: failure()  # Only run if the previous steps failed
+      #   run: echo "VERCEL_SKIP_DEPLOYMENT=true" >> $GITHUB_ENV
 
+  deployproduction:
+    needs: sonarcloud
+    name: Deploy Production
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - name: Install Vercel CLI
+        run: npm install --global vercel@canary
+      - name: Pull Vercel Environment Information
+        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Build Project Artifacts
+        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
+      - name: Deploy Project Artifacts to Vercel
+        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
